<a href="https://colab.research.google.com/github/hana-magdy/Face-Recognition/blob/main/FaceRecognitionTrial.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Imports:


In [1]:
from PIL import Image
from numpy import asarray
from sklearn.metrics import accuracy_score
import numpy as np
import glob
import cv2
import zipfile
import  os
from scipy.spatial import distance
from sklearn.neighbors import KNeighborsClassifier
from tabulate import tabulate
import pandas as pd
import matplotlib.pyplot as plt


In [ ]:
zip_ref = zipfile.ZipFile("archive (1).zip", "r")
zip_ref.extractall()
zip_ref.close()

In [2]:
 
y = []
Data_matrix = []
for i in range(1,41):
  folder = "s"
  folder+=str(i)
  y.append(i)
  files = glob.glob (folder)
  for j in range(1,11):
      file_name = folder + "/"+str(j)+".pgm"
      img = Image.open(file_name)
      data = np.array(img)
      #print(data)
      x = data.flatten()
      Data_matrix.append(x)
      #print(x.shape)
      print("Path")
      print(file_name)
      j=j+1
  j = 1
  i = i +1

Path
s1/1.pgm
Path
s1/2.pgm
Path
s1/3.pgm
Path
s1/4.pgm
Path
s1/5.pgm
Path
s1/6.pgm
Path
s1/7.pgm
Path
s1/8.pgm
Path
s1/9.pgm
Path
s1/10.pgm
Path
s2/1.pgm
Path
s2/2.pgm
Path
s2/3.pgm
Path
s2/4.pgm
Path
s2/5.pgm
Path
s2/6.pgm
Path
s2/7.pgm
Path
s2/8.pgm
Path
s2/9.pgm
Path
s2/10.pgm
Path
s3/1.pgm
Path
s3/2.pgm
Path
s3/3.pgm
Path
s3/4.pgm
Path
s3/5.pgm
Path
s3/6.pgm
Path
s3/7.pgm
Path
s3/8.pgm
Path
s3/9.pgm
Path
s3/10.pgm
Path
s4/1.pgm
Path
s4/2.pgm
Path
s4/3.pgm
Path
s4/4.pgm
Path
s4/5.pgm
Path
s4/6.pgm
Path
s4/7.pgm
Path
s4/8.pgm
Path
s4/9.pgm
Path
s4/10.pgm
Path
s5/1.pgm
Path
s5/2.pgm
Path
s5/3.pgm
Path
s5/4.pgm
Path
s5/5.pgm
Path
s5/6.pgm
Path
s5/7.pgm
Path
s5/8.pgm
Path
s5/9.pgm
Path
s5/10.pgm
Path
s6/1.pgm
Path
s6/2.pgm
Path
s6/3.pgm
Path
s6/4.pgm
Path
s6/5.pgm
Path
s6/6.pgm
Path
s6/7.pgm
Path
s6/8.pgm
Path
s6/9.pgm
Path
s6/10.pgm
Path
s7/1.pgm
Path
s7/2.pgm
Path
s7/3.pgm
Path
s7/4.pgm
Path
s7/5.pgm
Path
s7/6.pgm
Path
s7/7.pgm
Path
s7/8.pgm
Path
s7/9.pgm
Path
s7/10.pgm
Path
s8/1.pgm

In [3]:
Data_matrix = np.array(Data_matrix)
print("Total data:")
print(Data_matrix.shape)
print(Data_matrix)

print("Labels:")
print(y)


Total data:
(400, 10304)
[[ 48  49  45 ...  47  46  46]
 [ 60  60  62 ...  32  34  34]
 [ 39  44  53 ...  29  26  29]
 ...
 [125 119 124 ...  36  39  40]
 [119 120 120 ...  89  94  85]
 [125 124 124 ...  36  35  34]]
Labels:
[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40]


splitting the data:


In [4]:
Testing =  Data_matrix[::2]
Training = Data_matrix[1::2]
print("Training")
print(Training)

print("Testing")
print(Testing)

Training_Labels=[]
Original_Testing_Labels=[]
for i in range(1,41):
  for j in range(1,6):
    Training_Labels.append(i)
    Original_Testing_Labels.append(i)

print("Training Labels:")
print(Training_Labels)

Training
[[ 60  60  62 ...  32  34  34]
 [ 63  53  35 ...  41  10  24]
 [ 43  50  41 ... 158 153 169]
 ...
 [123 121 126 ...  40  35  42]
 [125 119 124 ...  36  39  40]
 [125 124 124 ...  36  35  34]]
Testing
[[ 48  49  45 ...  47  46  46]
 [ 39  44  53 ...  29  26  29]
 [ 64  76  80 ...  35  37  39]
 ...
 [128 125 125 ...  85  90  84]
 [129 127 133 ...  93  93  93]
 [119 120 120 ...  89  94  85]]
Training Labels:
[1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 3, 3, 3, 3, 3, 4, 4, 4, 4, 4, 5, 5, 5, 5, 5, 6, 6, 6, 6, 6, 7, 7, 7, 7, 7, 8, 8, 8, 8, 8, 9, 9, 9, 9, 9, 10, 10, 10, 10, 10, 11, 11, 11, 11, 11, 12, 12, 12, 12, 12, 13, 13, 13, 13, 13, 14, 14, 14, 14, 14, 15, 15, 15, 15, 15, 16, 16, 16, 16, 16, 17, 17, 17, 17, 17, 18, 18, 18, 18, 18, 19, 19, 19, 19, 19, 20, 20, 20, 20, 20, 21, 21, 21, 21, 21, 22, 22, 22, 22, 22, 23, 23, 23, 23, 23, 24, 24, 24, 24, 24, 25, 25, 25, 25, 25, 26, 26, 26, 26, 26, 27, 27, 27, 27, 27, 28, 28, 28, 28, 28, 29, 29, 29, 29, 29, 30, 30, 30, 30, 30, 31, 31, 31, 31, 31, 32, 32

### **PCA function:**


In [ ]:
def PCA_Prepration(Training):
  MeanMatrix=np.array(Training).mean(axis=0)
  print("Mean Matrix: ")
  print(MeanMatrix)
  print("Mean Matrix shape: ")
  print(MeanMatrix.shape)
  print("\n *********************************** \n")
  print("Centred Data: ")
  Centred_Data=np.array(Training-MeanMatrix)
  print(Centred_Data)
  print("\n *********************************** \n")
  print("Covariance matrix: ")
  Covariance_Matrix=np.cov(Centred_Data.T,bias=True)
  print(Covariance_Matrix)
  print("\n *********************************** \n")
  Eigenvalues,EigenVectors=np.linalg.eigh(Covariance_Matrix)
  print("Eigenvalues: ")
  print(Eigenvalues)
  print("\n *********************************** \n")
  print("Eigenvectors: ")
  print(EigenVectors)
  print("\n *********************************** \n")
  print("Sum of total EigenValues")
  SumEigenValues=Eigenvalues.sum()
  print(SumEigenValues)
  idx = np.argsort(Eigenvalues)[::-1]
  Sorted_eigenValues= Eigenvalues[idx]
  #Sorted_eigenValues=np.diagflat(Sorted_eigenValues)
  Sorted_eigenvectors= EigenVectors[:,idx]

  return  Sorted_eigenValues, Sorted_eigenvectors


In [ ]:
def PCA(Alpha):
  FractionalSum=0 
  FractionalVariance=0
  index=0
  for i in range(0,len(Sorted_eigenValues)):
    FractionalVariance=FractionalSum / SumEigenValues
    if  FractionalVariance < Alpha :
      index=i
      FractionalSum+=Sorted_eigenValues[i]
    else:
      break
 
  print("Fractional Variance")
  print(FractionalVariance)
  print("r= ",index)
          

  print("\n *********************************** \n")
  Reduced_Eigenvectors=Sorted_eigenvectors[:, 0:index+1]
  print("Reduced EigenVector= ")
  print(Reduced_Eigenvectors)
  print(Reduced_Eigenvectors.shape)
  print("\n *********************************** \n")

  Reduced_EigenvectorsT=np.transpose(Reduced_Eigenvectors)
  print("projection matrix= ")
  print(Reduced_EigenvectorsT) 

  print("\n *********************************** \n")
  print("Projected Training matrix = ")
  projected_training=np.dot(Centred_Data,Reduced_Eigenvectors)
  print(projected_training)

  print("\n *********************************** \n")
  Temp_Testing=np.subtract(Testing,Testing.mean(axis=0))
  print("Testing",Testing)
  print("Temp_Testing",Temp_Testing)
  projected_testing=np.dot(Temp_Testing,Reduced_Eigenvectors)
  print("Projected Testing matrix = ")
  print(projected_testing)
  print("\n *********************************** \n")
 
  return projected_training,projected_testing

In [ ]:
Sorted_eigenValues, Sorted_eigenvectors=PCA_Prepration(Training)

Mean Matrix: 
[85.12  84.89  85.165 ... 77.24  74.335 73.37 ]
Mean Matrix shape: 
(10304,)

 *********************************** 

Centred Data: 
[[-25.12  -24.89  -23.165 ... -45.24  -40.335 -39.37 ]
 [-22.12  -31.89  -50.165 ... -36.24  -64.335 -49.37 ]
 [-42.12  -34.89  -44.165 ...  80.76   78.665  95.63 ]
 ...
 [ 37.88   36.11   40.835 ... -37.24  -39.335 -31.37 ]
 [ 39.88   34.11   38.835 ... -41.24  -35.335 -33.37 ]
 [ 39.88   39.11   38.835 ... -41.24  -39.335 -39.37 ]]

 *********************************** 

Covariance matrix: 
[[1318.8756   1299.2282   1304.6652   ... -235.7588   -126.0752
   -75.5394  ]
 [1299.2282   1295.5879   1293.30315  ... -218.1036   -112.70315
   -64.3043  ]
 [1304.6652   1293.30315  1306.107775 ... -216.9946    -99.325275
   -49.28605 ]
 ...
 [-235.7588   -218.1036   -216.9946   ... 2505.0524   1995.4546
  1882.7162  ]
 [-126.0752   -112.70315   -99.325275 ... 1995.4546   1972.392775
  1859.56105 ]
 [ -75.5394    -64.3043    -49.28605  ... 1882.7162  

In [ ]:
print("PCA output for Alpha=0.8 :")
projected_training08,projected_testing08=PCA(0.8)

PCA output for Alpha=0.8 :


NameError: ignored

In [ ]:
print("PCA output for Alpha=0.85 :")
projected_training085,projected_testing085=PCA(0.85)

PCA output for Alpha=0.85 :
Fractional Variance
0.8523113375505037
r=  52

 *********************************** 

Reduced EigenVector= 
[[ 0.00124556 -0.01536171 -0.01891079 ... -0.00658215  0.0063633
  -0.00188005]
 [ 0.00126454 -0.01513146 -0.01911777 ... -0.00497546  0.00626057
  -0.00089457]
 [ 0.00156465 -0.01516195 -0.01903942 ... -0.00530911  0.00690086
  -0.00163866]
 ...
 [ 0.00873725  0.00961112 -0.01287451 ... -0.00490491 -0.01032198
  -0.00532878]
 [ 0.00721705  0.0077597  -0.01377318 ...  0.0029665  -0.00741123
  -0.00191385]
 [ 0.0084008   0.00692708 -0.01438815 ... -0.00282685 -0.00728419
  -0.00833635]]
(10304, 53)

 *********************************** 

projection matrix= 
[[ 0.00124556  0.00126454  0.00156465 ...  0.00873725  0.00721705
   0.0084008 ]
 [-0.01536171 -0.01513146 -0.01516195 ...  0.00961112  0.0077597
   0.00692708]
 [-0.01891079 -0.01911777 -0.01903942 ... -0.01287451 -0.01377318
  -0.01438815]
 ...
 [-0.00658215 -0.00497546 -0.00530911 ... -0.00490491 

In [ ]:
print("PCA output for Alpha=0.9:")
projected_training09,projected_testing09=PCA(0.9)

PCA output for Alpha=0.9:
Fractional Variance
0.9007600309473764
r=  76

 *********************************** 

Reduced EigenVector= 
[[ 0.00124556 -0.01536171 -0.01891079 ...  0.00179702 -0.0038579
   0.00149348]
 [ 0.00126454 -0.01513146 -0.01911777 ...  0.00188084 -0.00483295
   0.00235076]
 [ 0.00156465 -0.01516195 -0.01903942 ...  0.00152641 -0.0040227
   0.00128325]
 ...
 [ 0.00873725  0.00961112 -0.01287451 ...  0.0070125  -0.02963997
   0.0032255 ]
 [ 0.00721705  0.0077597  -0.01377318 ...  0.01557117 -0.02348247
   0.01523977]
 [ 0.0084008   0.00692708 -0.01438815 ...  0.00818988 -0.01151255
   0.00688259]]
(10304, 77)

 *********************************** 

projection matrix= 
[[ 0.00124556  0.00126454  0.00156465 ...  0.00873725  0.00721705
   0.0084008 ]
 [-0.01536171 -0.01513146 -0.01516195 ...  0.00961112  0.0077597
   0.00692708]
 [-0.01891079 -0.01911777 -0.01903942 ... -0.01287451 -0.01377318
  -0.01438815]
 ...
 [ 0.00179702  0.00188084  0.00152641 ...  0.0070125   0.

In [ ]:
print("PCA output for Alpha=0.95 :")
projected_training095,projected_testing095=PCA(0.95)

PCA output for Alpha=0.95 :
Fractional Variance
0.9500861567347986
r=  115

 *********************************** 

Reduced EigenVector= 
[[ 0.00124556 -0.01536171 -0.01891079 ... -0.0105497  -0.00116262
  -0.00499452]
 [ 0.00126454 -0.01513146 -0.01911777 ... -0.0063317  -0.00192066
  -0.00479632]
 [ 0.00156465 -0.01516195 -0.01903942 ... -0.00767535 -0.00365636
  -0.00746669]
 ...
 [ 0.00873725  0.00961112 -0.01287451 ...  0.00414923  0.00148975
  -0.01489488]
 [ 0.00721705  0.0077597  -0.01377318 ... -0.00193868 -0.0010741
  -0.02912841]
 [ 0.0084008   0.00692708 -0.01438815 ... -0.0059235  -0.00401374
  -0.038607  ]]
(10304, 116)

 *********************************** 

projection matrix= 
[[ 0.00124556  0.00126454  0.00156465 ...  0.00873725  0.00721705
   0.0084008 ]
 [-0.01536171 -0.01513146 -0.01516195 ...  0.00961112  0.0077597
   0.00692708]
 [-0.01891079 -0.01911777 -0.01903942 ... -0.01287451 -0.01377318
  -0.01438815]
 ...
 [-0.0105497  -0.0063317  -0.00767535 ...  0.0041492

In [15]:
def Label_prediction(k,ProjectedTraining , ProjectedTesting):

  model = KNeighborsClassifier(n_neighbors=k)
  model.fit(ProjectedTraining,np.array(Training_Labels))
  Tested_Labels= model.predict(ProjectedTesting)

  return Tested_Labels

In [ ]:
print("Tested labels for 0.8=")
Tested_Labels08=Label_prediction (1,projected_training08,projected_testing08)
print(Tested_Labels08)

print("\n *********************************** \n")

print("Tested labels for 0.85=")
Tested_Labels085=Label_prediction (1,projected_training085,projected_testing085)
print(Tested_Labels085)

print("\n *********************************** \n")

print("Tested labels for 0.9=")
Tested_Labels09=Label_prediction (1,projected_training09,projected_testing09)
print(Tested_Labels09)

print("\n *********************************** \n")

print("Tested labels for 0.95=")
Tested_Labels095=Label_prediction (1,projected_training095,projected_testing095)
print(Tested_Labels095)

Tested labels for 0.8=
[16  2  1  1  1  2  2  2  2  2  3  3  3  3  3  4  4  4  4  4  5  5  5  5
  5  6  6  6  6  6  7  7  7  7  7  8  8  8  8  8  9  9  9  9  9 10 10 10
 10 38 11 11 11 11 11 12 12 12 12 12 13 13 13 13 13 14 14 14 14 14 15 15
 15 15 15 16 16 16 16 16 17 17 17 17 17 18 18 18 18 18 19 19 19 19 36 20
 20  3 20 20 21 21 21 21 21 22 22 22 22 22 23 23 23 23 23 24 24 24 24 24
 25 25 25 25 25 26 26 26 26 26 27 27 27 27 27 28 28 28 28 28 29 29 29 29
 29 30 30 30 30 30 31 31 31 21 31 32 32 32  2 32 33 33 33 33 33 34 34 34
 34 34 40 15 35 35 35  7 36  7 36 36 37 37 37 37 37 38 38 38 38 38 39 39
 39 39 39 40 40  5  5  5]

 *********************************** 

Tested labels for 0.85=
[16  2  1  1  1  2  2  2  2  2  3  3  3  3  3  4  4  4  4  4  5  5  5  5
  5  6  6  6  6  6  7  7  7  7  7  8  8  8  8  8  9  9  9  9  9 10 10 10
 10 38 11 11 11 11 11 12 12 12 12 12 13 13 13 13 13 14 14 14 14 14 15 15
 15 15 15 16 16 16 16 16 17 17 17 17 17 18 18 18 18 18 19 19 19 19 36 20
 20  3 20 2

In [ ]:
 print("Accuracy of 0.8 =")
 Accuracy08 = accuracy_score(Original_Testing_Labels, Tested_Labels08)
 print(Accuracy08*100,"%")

 print("Accuracy of 0.85 =")
 Accuracy085 = accuracy_score(Original_Testing_Labels, Tested_Labels085)
 print(Accuracy085*100,"%")  

 print("Accuracy of 0.9 =")
 Accuracy09 = accuracy_score(Original_Testing_Labels, Tested_Labels09)
 print(Accuracy09*100,"%")

 print("Accuracy of 0.95 =")
 Accuracy095= accuracy_score(Original_Testing_Labels, Tested_Labels095)
 print(Accuracy095*100,"%")

Accuracy of 0.8 =
93.0 %
Accuracy of 0.85 =
93.5 %
Accuracy of 0.9 =
94.0 %
Accuracy of 0.95 =
93.5 %



### **LDA**





In [5]:
#1
ListOfClasses=[]
for i in range(0,40):
  ListOfClasses.append(Training[5*i:5*(i+1),:])

  
  
#print(ListOfClasses)
#2
ListOfMeans=[]
for i in range(0,40):
  ListOfMeans.append(np.array(ListOfClasses[i]).mean(axis=0))

print("List of means length : ",len(ListOfMeans))  
print("List of means : ",ListOfMeans)

#3
OverallMean=np.array(Training).mean(axis=0)
print("Overall mean =",OverallMean)
Sb=np.zeros((10304,10304))
for i in range(0,40):
  expression=(np.outer((ListOfMeans[i]-OverallMean),np.array((ListOfMeans[i]-OverallMean)).T))
  Sb=Sb+ expression
Sb=5*Sb  
print("sb= ",Sb)

#4
ListOfCentredData=[]
for i in range(0,40):
  ListOfCentredData.append(ListOfClasses[i]-np.array(ListOfMeans[i]).T)

print("List of centred data ",ListOfCentredData)

#5
ListOfScatterMatrcies=np.zeros((10304,10304))
for j in range(0,40):
 expression=np.dot(np.array(ListOfCentredData[j]).T,np.array(ListOfCentredData[j]))
 ListOfScatterMatrcies=ListOfScatterMatrcies+expression
   
print("S= ",ListOfScatterMatrcies.shape)
print(ListOfScatterMatrcies)




List of means length :  40
List of means :  [array([48.8, 48. , 40.6, ..., 62.2, 56. , 59.4]), array([35.2, 35.8, 35.6, ..., 71.8, 71.6, 71.6]), array([105.2, 104. , 107.4, ...,  50. ,  48.4,  50. ]), array([118.6, 118.8, 118. , ...,  70.8,  69.4,  69.2]), array([128.8, 129. , 127.8, ...,  72.6,  71.8,  72.8]), array([153.4, 152.8, 152.2, ..., 103.6, 103.8, 103. ]), array([56.6, 57.2, 57.6, ..., 64. , 65. , 65.4]), array([122. , 118.6, 119.8, ...,  59.8,  56.8,  59. ]), array([109.8, 111.4, 110.4, ...,  84. ,  82.4,  83.2]), array([134.2, 130. , 132.6, ...,  26. ,  30.4,  32.4]), array([46.4, 47. , 46.4, ..., 34. , 34. , 37.6]), array([104.6, 106. , 105.4, ...,  38.8,  40.6,  33. ]), array([107.6, 109.2, 108. , ...,  20.6,  25.8,  23.8]), array([ 45.8,  47.2,  46.8, ..., 142.2, 142.6, 123.4]), array([72.4, 72.2, 71.4, ..., 71.8, 49. , 54. ]), array([60. , 59. , 61.4, ..., 64.6, 64.6, 60.4]), array([49.4, 49.6, 51.4, ..., 42.2, 46.8, 46. ]), array([121.2, 120.6, 122.2, ...,  73.6,  74. 

In [7]:
inv=np.linalg.inv(ListOfScatterMatrcies)
math_symm = (np.triu_indices(len(inv), 1))
inv[math_symm]=np.tril(inv, -1).T[math_symm]

print(inv)

[[ 2.41927224e+10 -1.08670945e+10  2.54571078e+10 ...  3.64317151e+09
  -4.19315811e+09 -1.87594061e+09]
 [-1.08670945e+10  1.95704296e+10 -2.15524699e+10 ... -6.67123128e+08
   4.87576934e+08 -8.23215873e+08]
 [ 2.54571078e+10 -2.15524699e+10  1.30523468e+10 ...  1.85670327e+09
  -2.83395492e+09 -1.47503002e+09]
 ...
 [ 3.64317151e+09 -6.67123128e+08  1.85670327e+09 ... -2.08734659e+09
   2.57987819e+09  6.41637579e+08]
 [-4.19315811e+09  4.87576934e+08 -2.83395492e+09 ...  2.57987819e+09
  -6.18200646e+09  3.90041512e+08]
 [-1.87594061e+09 -8.23215873e+08 -1.47503002e+09 ...  6.41637579e+08
   3.90041512e+08 -5.22071836e+08]]


In [8]:
s_1_b=np.dot(inv,Sb)




[[-3.92517924e+15 -3.97159571e+15 -3.84405827e+15 ... -6.67481770e+14
  -2.25360090e+15 -9.76205022e+14]
 [-2.34567651e+15 -2.38995980e+15 -2.15789869e+15 ...  2.05696221e+15
   9.53844506e+14  1.04112749e+15]
 [-6.24457868e+15 -6.27436293e+15 -6.05200786e+15 ...  4.52820028e+14
  -1.10054112e+15 -2.49663985e+14]
 ...
 [ 4.27318739e+15  4.31769286e+15  4.38372799e+15 ...  9.97069720e+15
   7.47922023e+15  6.61051980e+15]
 [-8.11195835e+15 -8.27061400e+15 -8.19195501e+15 ... -1.33107902e+16
  -1.02617986e+16 -9.08604286e+15]
 [-2.74238517e+15 -2.82355977e+15 -2.80150292e+15 ... -6.87271818e+15
  -6.41174803e+15 -5.87995514e+15]]


In [10]:
math_symm = (np.triu_indices(len(s_1_b), 1))
s_1_b[math_symm]=np.tril(s_1_b, -1).T[math_symm]
print(s_1_b)

[[-3.92517924e+15 -2.34567651e+15 -6.24457868e+15 ...  4.27318739e+15
  -8.11195835e+15 -2.74238517e+15]
 [-2.34567651e+15 -2.38995980e+15 -6.27436293e+15 ...  4.31769286e+15
  -8.27061400e+15 -2.82355977e+15]
 [-6.24457868e+15 -6.27436293e+15 -6.05200786e+15 ...  4.38372799e+15
  -8.19195501e+15 -2.80150292e+15]
 ...
 [ 4.27318739e+15  4.31769286e+15  4.38372799e+15 ...  9.97069720e+15
  -1.33107902e+16 -6.87271818e+15]
 [-8.11195835e+15 -8.27061400e+15 -8.19195501e+15 ... -1.33107902e+16
  -1.02617986e+16 -6.41174803e+15]
 [-2.74238517e+15 -2.82355977e+15 -2.80150292e+15 ... -6.87271818e+15
  -6.41174803e+15 -5.87995514e+15]]


In [11]:
EigenValues,EigenVector=np.linalg.eigh(s_1_b)
print(EigenValues.shape)
print(EigenValues)
print(EigenVector.shape)
print(EigenVector)

(10304,)
[-2.77146596e+19 -1.90595178e+19 -1.57557444e+19 ...  1.62094715e+19
  1.92151487e+19  2.81495349e+19]
(10304, 10304)
[[-0.01719123  0.00909356 -0.02676178 ...  0.02664646 -0.00898708
   0.01731865]
 [-0.01698555  0.00913003 -0.02685456 ...  0.02673725 -0.00905747
   0.017107  ]
 [-0.01720716  0.0091637  -0.02634558 ...  0.02623938 -0.0090471
   0.01733775]
 ...
 [ 0.01519214  0.02567703 -0.00283949 ... -0.00166007  0.02610118
   0.01440244]
 [-0.01791855 -0.02957834 -0.00174358 ... -0.00283793 -0.02984239
  -0.01700352]
 [-0.00459661 -0.00821291 -0.00191172 ... -0.00178508 -0.00816821
  -0.00445732]]


In [12]:
idx = np.argsort(EigenValues)[::-1]
Sorted_eigenValues= EigenValues[idx]
Sorted_eigenvectors= EigenVector[:,idx]

Reduced_Dimensions=Sorted_eigenvectors[0:39]


LDAProjectionMatrix=Reduced_Dimensions.T
print(LDAProjectionMatrix)


[[ 0.01731865  0.017107    0.01733775 ... -0.00826129 -0.00772953
  -0.00751452]
 [-0.00898708 -0.00905747 -0.0090471  ... -0.00933998 -0.00860887
  -0.00771004]
 [ 0.02664646  0.02673725  0.02623938 ...  0.01610841  0.01477417
   0.0159703 ]
 ...
 [-0.02676178 -0.02685456 -0.02634558 ... -0.0170666  -0.01480786
  -0.01569157]
 [ 0.00909356  0.00913003  0.0091637  ...  0.00895887  0.00800696
   0.00695244]
 [-0.01719123 -0.01698555 -0.01720716 ...  0.00795673  0.00768434
   0.00755853]]


In [13]:
LDAProjectedTraining=np.dot(Training,LDAProjectionMatrix)
print(LDAProjectedTraining)
print(LDAProjectedTraining.shape)
LDAProjectedTesting=np.dot(Testing,LDAProjectionMatrix)
print(LDAProjectedTesting)
print(LDAProjectedTesting.shape)

[[  11.93511642   30.87641889  166.15323611 ...   58.79896321
    -8.89304079  123.48869242]
 [ -63.26706298  -57.06554497   70.04464645 ...  184.76254506
    34.98155037   33.77875472]
 [ -19.72374092  -59.49694256   50.15809164 ...  183.34983256
    18.2941753   108.89997014]
 ...
 [  70.85117213 -100.47747556  130.17942181 ...   64.7868816
    63.57019454  -45.55198244]
 [  59.21787855 -107.29107506  129.08204462 ...   92.03545402
     3.69750307  -14.68856274]
 [  44.541023    -66.92704733  109.1434135  ...   40.22626668
    47.67960014   11.65282923]]
(200, 39)
[[ 32.05624323 -80.71355963  90.91108358 ... 101.84789291  57.87151351
   62.02995027]
 [ -3.25433331 -91.82892916  74.04238544 ...  54.16240563  58.02963133
  100.16393968]
 [-58.32133919 -35.46455606 109.25571518 ... 124.81067698  21.70591883
   63.97910939]
 ...
 [ 26.92925601 -80.95000773 138.92234214 ...  96.24601983  45.0825278
  -22.03996982]
 [-50.68589795 -15.26458804 143.13489874 ...  90.32259237  19.57888858
   4

In [16]:
LDAPredictedLabels=Label_prediction(1,LDAProjectedTraining,LDAProjectedTesting)
print(LDAPredictedLabels)


[16 32 13 19  1  2  2  2  2  2  3  3 37  3  3  4  4  4  4  4  5  5  5  5
  5  6  6  6  6  6  7  7  7  7  7  8  8  8  8  8  9  9  9  9  9 10 10 10
 10 30 11 11 11 11 11 12 37 12 12 12 13 13 13 13 13 14 14 14 14 14 15 15
 15 15 15 24 16 16 16  2 17 17 17 17 17 18 18 18 18 18 19 19 19 19 15 20
 20  4  4 20 21 21 21  9 21 22 22 22 22 22 23  9 30 23 23 24 24  8 24 24
 25 25 25 25 25 26 26 26 37 26 27 27 27 27 27 28 28 28 28 28 29 29 29 29
 39 30 30 30 30 30 31 31 31 31 31 32  5 32  2 32 39 39 33 33 33 34 34 34
 34 34 40  5  5 35 32 36 36  3 36 36 37 28 37 37 37 38 38 38 38 23 39 39
 39 39 39 40 40 40  5  5]


In [17]:
LDA_Accuracy1 = accuracy_score(Original_Testing_Labels, LDAPredictedLabels)
print("Accuracy1 = ",LDA_Accuracy1*100, "%")

Accuracy1 =  84.5 %


### **Classfier tunning**

In [ ]:
AccuracyLDA=[]

AccuracyLDA.append([1,LDA_Accuracy1])

LDAPredictedLabels3=Label_prediction(3,LDAProjectedTraining,LDAProjectedTesting)
LDA_Accuracy3 = accuracy_score(Original_Testing_Labels, LDAPredictedLabels3)
AccuracyLDA.append([3,LDA_Accuracy3])
print(LDAPredictedLabels3)

print("\n *********************************** \n")

LDAPredictedLabels5=Label_prediction(5,LDAProjectedTraining,LDAProjectedTesting)
LDA_Accuracy5 = accuracy_score(Original_Testing_Labels, LDAPredictedLabels5)
AccuracyLDA.append([5,LDA_Accuracy5])
print(LDAPredictedLabels5)

print("\n *********************************** \n")

LDAPredictedLabels7=Label_prediction(7,LDAProjectedTraining,LDAProjectedTesting)
LDA_Accuracy7 = accuracy_score(Original_Testing_Labels, LDAPredictedLabels7)
AccuracyLDA.append([7,LDA_Accuracy7])
print(LDAPredictedLabels7)



[ 1 24  1  1  1 36  2 19  2 15  3  3  5  3  3  4  4  4 23  4  5  5  5 40
  5  6  6  6  6  6  7  7  7  7  7  8  8  8  8  8  9  9  9  9  4 10 10 10
 10 10 11 11 11 11 11 12 12 12 12 12 40  5 13 13  3 14 14 14 14 14 15 15
  9 25 30 11 16  7 16  1  7 17 17 17 17 18  5 18 18 18 19 19 19 19 19  4
 29 20 20 20 21 21 21 21 21 22 22 22 22 22 23 23 23 23 23 24 24 16 24 24
 25 25  5 25 25 26  5 26 26  4 27 27 27 27 27 28 28 22 22  7 29 29 29 29
  4 30  9 30 30 30 31 31 31 33  9  7 32 32  1 32 39  9 39 21 21 34 34 34
 34 34 35 15 25 15 35  7 19  7 36  7 26  5 37 15  5 38  4  9 23 38 39 39
 39 39 39  5  4  5  5  5]

 *********************************** 

[ 1  1  1  1  1  7  2 19  2 15  3  3  5  3  3  4  4  4 23  4  5  5  5  5
  5  6  6  6  6  6  7  7  7  7  7  8  8  8  8  8  9  9  9  9  4 10 10 10
 10 10 11 22 11 11 11 12  3 12 12 12 40 18 13 13  3 14 14 14 14 14 15 15
 25 25 30 17 16  7 16 16  7 17  7 17 17 18  5 18 18 18 19 19  7  7  7 23
 29 20 20 20 21 21 21 21 21 22 22 22 22 22 23 23 23 23 23 

In [ ]:

print (tabulate(AccuracyLDA, headers=["K", "Accuracy"]))


  K    Accuracy
---  ----------
  1       0.805
  3       0.71
  5       0.695
  7       0.655


In [ ]:
PCAPredictedLabels08=[]
PCAPredictedLabels085=[]
PCAPredictedLabels09=[]
PCAPredictedLabels095=[]
PCA_Accuracy08=[]
PCA_Accuracy085=[]
PCA_Accuracy09=[]
PCA_Accuracy095=[]
K=[1,3,5,7]
for i in range(0,4):
  PCAPredictedLabels08.append(Label_prediction(K[i],projected_training08,projected_testing08))
  PCAPredictedLabels085.append(Label_prediction(K[i],projected_training085,projected_testing085))
  PCAPredictedLabels09.append(Label_prediction(K[i],projected_training09,projected_testing09))
  PCAPredictedLabels095.append(Label_prediction(K[i],projected_training095,projected_testing095))
for i in range(0,4):
  PCA_Accuracy08.append([K[i],accuracy_score(Original_Testing_Labels, PCAPredictedLabels08[i])])
  PCA_Accuracy085.append([K[i],accuracy_score(Original_Testing_Labels, PCAPredictedLabels085[i])])
  PCA_Accuracy09.append([K[i],accuracy_score(Original_Testing_Labels, PCAPredictedLabels09[i])])
  PCA_Accuracy095.append([K[i],accuracy_score(Original_Testing_Labels, PCAPredictedLabels095[i])])





print("Classifying accuracy with respect to k for PCA (Alpha=0.8) \n")
print (tabulate(PCA_Accuracy08, headers=["K", "Accuracy"]))

print("\n Classifying accuracy with respect to k for PCA (Alpha=0.85) \n")
print (tabulate(PCA_Accuracy085, headers=["K", "Accuracy"]))

print("\n Classifying accuracy with respect to k for PCA (Alpha=0.9) \n")
print (tabulate(PCA_Accuracy09, headers=["K", "Accuracy"]))

print("\n Classifying accuracy with respect to k for PCA (Alpha=0.95) \n")
print (tabulate(PCA_Accuracy095, headers=["K", "Accuracy"]))

Classifying accuracy with respect to k for PCA (Alpha=0.8) 

  K    Accuracy
---  ----------
  1       0.93
  3       0.855
  5       0.805
  7       0.78

 Classifying accuracy with respect to k for PCA (Alpha=0.85) 

  K    Accuracy
---  ----------
  1       0.94
  3       0.855
  5       0.83
  7       0.775

 Classifying accuracy with respect to k for PCA (Alpha=0.9) 

  K    Accuracy
---  ----------
  1       0.945
  3       0.85
  5       0.815
  7       0.755

 Classifying accuracy with respect to k for PCA (Alpha=0.95) 

  K    Accuracy
---  ----------
  1       0.935
  3       0.845
  5       0.815
  7       0.74


### **Non-Faces/Faces**

In [ ]:
img = Image.open('/content/dog (3).pgm')     
data = np.array(img)     
print(data.shape)     
x = data.flatten()         
print(x.shape)
  

(92, 112)
(10304,)
